# Generated by Django 3.0.3 on 2020-02-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiario',
            name='nome',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
