# Generated by Django 3.0.3 on 2020-02-09 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiario', '0002_apiario_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiario',
            name='apicoltore',
        ),
    ]
