# Generated by Django 3.0.3 on 2020-02-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arnia', '0002_arnia_nome'),
        ('apiario', '0003_remove_apiario_apicoltore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiario',
            name='arnie',
            field=models.ManyToManyField(related_name='apiari', to='arnia.Arnia'),
        ),
    ]
