# Generated by Django 3.0.3 on 2020-02-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiario', '0003_remove_apiario_apicoltore'),
        ('apicoltore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicoltore',
            name='apiari',
            field=models.ManyToManyField(to='apiario.Apiario'),
        ),
    ]
